### ISSUE TITLE
Could you please provide an `impl std::error::Error for rasn::ber::de::Error`?

### ISSUE THREAD

**Issue by hcldan** [librasn/rasn#119]
https://github.com/dtolnay/thiserror/issues/235

I'm not sure why snafu doesn't do this for you... but I'd like to be able to use your errors with `thiserror`.

**Comment by XAMPPRocky** [comment]
Tried adding this, and it seems `Error` is still unavailable in core.

**Comment by Nicceboy** [comment]
Here is the tracking issue https://github.com/rust-lang/rust/issues/103765 of adding it to the `core`. Seems like it has made into the unstable.

**Comment by XAMPPRocky** [comment]
As of 1.81.0 this can now be added.

**Comment by Nicceboy** [comment]
Relevant Snafu PR https://github.com/shepmaster/snafu/pull/463

**Comment by shepmaster** [comment]
Updating to [SNAFU 0.8.5](https://crates.io/crates/snafu/0.8.5) and adding the `rust_1_81` feature should now implement `core::error::Error`.

**Comment by XAMPPRocky** [comment]
@shepmaster Thank you for your work on this, I've now pushed an update that includes snafu 0.8.5 with the feature. 🎉
