### ISSUE TITLE
Breaking change in 0.12.6 breaks compilation of apple-codesign

### ISSUE THREAD

**Issue by roblabla** [librasn/rasn#233]
CC https://github.com/indygreg/apple-platform-rs/issues/137

https://github.com/librasn/rasn/commit/6733000a7b2b850ba2f14c4aa34c9a415f3374cf#diff-d1ebeac1717b0f39fcc6191badf3eeba3f2db16ffa4620ee04694496788c20eeR634 this commit introduced a breaking change by changing the signature of the `Decoder::decode_sequence` function, specifically in the number of arguments it takes.

See this documentation:

- https://docs.rs/rasn/0.12.5/rasn/trait.Decoder.html#tymethod.decode_sequence
- https://docs.rs/rasn/0.12.6/rasn/trait.Decoder.html#tymethod.decode_sequence

This breaks the build of apple-codesign.

Would it be possible to yank the 0.12.6 and re-release as 0.13.0?

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I've now yanked the version.
