### ISSUE TITLE
Update to `syn` 2

### ISSUE THREAD

**Issue by XAMPPRocky** [librasn/rasn#317]

**Comment by shahn** [comment]
I was wanting to take a stab at this, but when I did I stumbled across option_type, which seems to be undocumented and entirely untested. It seems to give the option to specify some_variant and none_variant for an optional type, but both are entirely unused in the code base. Is this an unfinished idea, left in the code? Should it be implemented somehow and tested, or is it OK to remove?

**Comment by XAMPPRocky** [comment]
@shahn It is a leftover from an older version, I would recommend making a first PR removing it, and then following up with the syn 2 update :)
